app/images/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from . import views
from .sitemap import WebImageSitemap 

app_name = "images"
urlpatterns = [
    path("upload", views.upload, name="upload"),
    path("add", views.add, name="add"),
    path("delete/<str:id>", views.delete, name="delete"),
    path("update-category/<str:id>", views.update_category, name="update_category"),
    path("update-tags/<str:id>", views.update_tags, name="update_tags"),
    path("view/<str:id>", views.view, name="view"),
]

app/maierbox/urls.py
from django.contrib import auth
from django.urls import include, path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.sitemaps.views import sitemap
from images.sitemap import WebImageSitemap
from posts.sitemap import PostSitemap
from albums.sitemap import WebImageAlbumSitemap
from categories.sitemap import ImageCategorySitemap
from .sitemap import StaticSitemap

sitemaps = {
    'sitemaps': {
        'static': StaticSitemap,
        'post': PostSitemap,
        'album': WebImageAlbumSitemap,
        'image': WebImageSitemap,
        'category': ImageCategorySitemap,
    }
}

urlpatterns = [
    path("", views.index, name="index"),
    path("peepers", views.eyes, name='peepers'),
    path("images/", include("images.urls")),
    path("tags/", include("tags.urls")),
    path("categories/", include("categories.urls")),
    path("watermarks/", include("watermarks.urls")),
    path("albums/", include("albums.urls")),
    path("posts/", include("posts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('sitemap.xml', sitemap, sitemaps, name='django.contrib.sitemaps.views.sitemap'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/posts/urls.py
from django.urls import path, re_path
from . import views

app_name = "posts"
urlpatterns = [
    re_path(r"^view/(?P<id>[^/]+)/?$", views.view, name="view"),
    path("add", views.add, name="add"),
    path("create", views.create, name="create"),
    path("edit/<str:id>", views.edit, name="edit"),
    path("update/<str:id>", views.update, name="update"),
    path("delete/<str:id>", views.delete, name="delete"),
    path("", views.index, name="index"),
]

app/tags/urls.py
from django.urls import path
from . import views

app_name = "tags"
urlpatterns = [
    path("list", views.list, name="list"),
    path("images/<str:tag>", views.view_images, name="view_images"),
]

app/posts/models.py
from django.db import models
from categories.models import Category
from tags.models import Tag
from albums.models import WebImageAlbum
from uuid import uuid4
from django.urls import reverse

TITLE_MAX_LENGTH=64
PREVIEW_LENGTH=256

class Post(models.Model):

    id = models.UUIDField(
        primary_key=True,
        null=False,
        blank=False,
        default=uuid4,
        editable=False
    )
    title = models.CharField(
        null=False,
        blank=False,
        editable=False,
        max_length=TITLE_MAX_LENGTH
    )
    content = models.TextField(
        null=False,
        blank=True,
        editable=True,
    )
    tags = models.ManyToManyField(
        blank=True,
        to=Tag,
    )
    category = models.ForeignKey(
        to=Category,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    album = models.ForeignKey(
        to=WebImageAlbum,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    date_modified = models.DateTimeField(
        null=False,
        blank=False,
        auto_now=True,
        editable=False,
    )
    date_created = models.DateTimeField(
        null=False,
        blank=False,
        auto_now_add=True,
        editable=False,
    )
    date_published = models.DateTimeField(
        null=True,
        blank=False,
        editable=False,
    )
    published = models.BooleanField(
        null=False,
        blank=False,
        default=True
    )
    unlisted = models.BooleanField(
        null=False,
        blank=False,
        default=False
    )

    def preview(self):
        length = len(self.content)
        cutoff = False
        if length > PREVIEW_LENGTH:
            length = PREVIEW_LENGTH
            cutoff = True
        preview = self.content[:length]
        if cutoff:
            preview = preview + '...'
        return preview

    def hasImages(self):
        return self.album and self.album.hasImages()
    
    def get_absolute_url(self):
        return reverse("posts:view", args=[self.id])

app/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseNotAllowed, HttpRequest, Http404
from django.core.paginator import Paginator
from django.utils.dateparse import parse_date
from urllib.parse import urlencode
from maierbox.util import JsonErrorResponse
from .models import Post
from images.models import WebImage
from albums.models import WebImageAlbum
from markdown2 import markdown
import uuid

MAX_POSTS = 6
MAX_PER_PAGE = 100

def index(request: HttpRequest):
    
    if request.method != "GET":
        return HttpResponseNotAllowed(['GET'])
    
    page_number = request.GET.get('page', 1)
    try:
        page_number = int(page_number)
    except (TypeError, ValueError):
        page_number = 1

    per_page = request.GET.get('max', MAX_POSTS)
    try:
        per_page = int(per_page)
    except (TypeError, ValueError):
        per_page = MAX_POSTS
    if per_page < 1:
        per_page = MAX_POSTS
    if per_page > MAX_PER_PAGE:
        per_page = MAX_PER_PAGE

    date_from_raw = request.GET.get('start', '').strip()
    date_to_raw = request.GET.get('end', '').strip()
    date_from = parse_date(date_from_raw) if date_from_raw else None
    date_to = parse_date(date_to_raw) if date_to_raw else None
    if date_from and date_to and date_from > date_to:
        date_from, date_to = date_to, date_from
        date_from_raw, date_to_raw = date_to_raw, date_from_raw

    sort = request.GET.get('sort', 'newest')
    sort_options = {
        'newest': '-date_created',
        'oldest': 'date_created',
    }
    order_by = sort_options.get(sort, '-date_created')

    posts = Post.objects.filter(published=True, unlisted=False)
    if date_from:
        posts = posts.filter(date_created__date__gte=date_from)
    if date_to:
        posts = posts.filter(date_created__date__lte=date_to)

    paginator = Paginator(
        posts.order_by(order_by),
        per_page=per_page,
    )

    page = paginator.get_page(page_number)

    query_params = {
        'max': per_page,
        'sort': sort if sort in sort_options else 'newest',
    }
    if date_from and date_from_raw:
        query_params['start'] = date_from_raw
    if date_to and date_to_raw:
        query_params['end'] = date_to_raw
    query_string = urlencode(query_params)
    pagination_query = f"&{query_string}" if query_string else ""

    context = {
        'page': page,
        'pagination_query': pagination_query,
        'filters': {
            'start': date_from_raw if date_from else '',
            'end': date_to_raw if date_to else '',
            'sort': sort if sort in sort_options else 'newest',
            'max': per_page,
        },
        'per_page_options': [6, 12, 24, 48],
    }
    return render(request, 'posts/index.html', context)

def view(request: HttpRequest, id):
    post = get_object_or_404(Post, id=id)

    if not post.published and not request.user.is_authenticated:
        raise Http404
    
    content = markdown(post.content, extras=["tables", "break-on-newline"])
    context = {
        'id': post.id,
        'title': post.title,
        'date': post.date_created,
        'abs_url': post.get_absolute_url(),
        'content': content,
    }
    if (post.album and post.album.images.count() > 0):
        context['images'] = post.album.images.all().order_by('date_created')
        context['preview'] = request.build_absolute_uri(post.album.images.first().thumbnail.url)
    return render(request, 'posts/view.html', context)

@login_required
def add(request: HttpRequest):
    return render(request, 'posts/add.html')

@login_required
def create(request: HttpRequest):

    if request.method != "POST":
        return HttpResponseNotAllowed(['POST'])
    
    if not 'title' in request.POST:
        JsonErrorResponse(
            data='The "title" field is required'
        )
    title = request.POST['title']

    if not 'content' in request.POST:
        JsonErrorResponse(
            data='The "content" field is required'
        )
    content = request.POST['content']
    
    # Create album if images are specified
    album = None
    if 'images' in request.POST and len(request.POST['images']) > 0:
        webimages = []
        failed = []
        for image_id in request.POST['images'].split(','):
            try:
                webimage = WebImage.objects.get(id=image_id)
                webimages.append(webimage)
            except Exception as e:
                failed.append(image_id)
        if len(failed) > 0:
            print(f'FAILED: {",".join(failed)}')
            return JsonErrorResponse(
                data=f'The following WebImage IDs did not match any existing WebImages: {", ".join(failed)}'
            )
        album = WebImageAlbum(title=title)
        album.save()
        for webimage in webimages:
            album.images.add(webimage)
        album.save()
    post = Post(
        title=title,
        content=content,
        album=album,
    )
    post.save()
    data = {
        'post': post.id
    }
    return JsonResponse(data)

@login_required
def edit(request: HttpRequest, id):
    post = get_object_or_404(Post, id=id)
    context = {'post': post}
    return render(request, 'posts/edit.html', context)

@login_required
def update(request: HttpRequest, id):
    post = get_object_or_404(Post, id=id)

    if request.method != "POST":
        return HttpResponseNotAllowed(['POST'])
    
    if not 'title' in request.POST:
        JsonErrorResponse(
            data='The "title" field is required'
        )
    title = request.POST['title']

    if not 'content' in request.POST:
        JsonErrorResponse(
            data='The "content" field is required'
        )
    content = request.POST['content']
    
    # Create album if images are specified
    if 'images' in request.POST and len(request.POST['images']) > 0:
        webimages = []
        failed = []
        for image_id in request.POST['images'].split(','):
            try:
                webimage = WebImage.objects.get(id=image_id)
                webimages.append(webimage)
            except Exception as e:
                failed.append(image_id)
        
        if len(failed) > 0:
            print(f'FAILED: {",".join(failed)}')
            return JsonErrorResponse(
                data=f'The following WebImage IDs did not match any existing WebImages: {", ".join(failed)}'
            )
        if post.album:
            post.album.images.clear()
            post.album.save()
        else:
            post.album = WebImageAlbum(title=title)
            post.album.save()
        for webimage in webimages:
            post.album.images.add(webimage)
        post.album.save()
    post.title = title
    post.content = content
    post.save()
    data = {
        'post': post.id
    }
    return JsonResponse(data)

@login_required
def delete(request: HttpRequest, id):
    if request.method != "DELETE":
        return HttpResponseNotAllowed(['DELETE'])
    
    post = get_object_or_404(Post, id=id)
    post.delete()
    return redirect('/posts')

app/posts/templates/posts/add.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'simplemde.css' %}">
<script src="{% static 'simplemde.js' %}"></script>
<script src="{% static 'images/image_metadata_selects.js' %}"></script>
<script src="{% static 'images/upload.js' %}"></script>
<script src="{% static 'posts/post.js' %}"></script>
<title>Create Post</title>
{% endblock %}
{% block body %}
<div id="post_form" class="post_form"></div>
<script>
    post_form = new PostUploadForm(document.getElementById('post_form'));
</script>
{% endblock %}

app/posts/templates/posts/edit.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'simplemde.css' %}">
<script src="{% static 'simplemde.js' %}"></script>
<script src="{% static 'images/image_metadata_selects.js' %}"></script>
<script src="{% static 'images/upload.js' %}"></script>
<script src="{% static 'posts/post.js' %}"></script>
<title>Edit Post</title>
{% endblock %}
{% block body %}
<div id="post_edit_form" class="post_form"></div>
<div id="original_post" class="original_post" hidden="true">
    <div id="original_post_title" class="original_post_title">{{ post.title }}</div>
    <div id="original_post_content" class="original_post_content">{{ post.content }}</div>
    {% if post.hasImages %}
    <div id="original_post_images" class="original_post_images">
        {% for image in post.album.images.all %}
        <div class="original_post_image"
             data-id="{{ image.id }}"
             data-category="{{ image.category|default_if_none:'' }}"
             data-watermark="{% if image.watermark %}{{ image.watermark.id }}{% endif %}"
             data-tags="{% for tag in image.tags.all %}{{ tag.tag }}{% if not forloop.last %},{% endif %}{% endfor %}">
            {{ image.id }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
<script>
    let original_title = document.getElementById('original_post_title').innerHTML;
    let original_content = document.getElementById('original_post_content').innerHTML;
    let original_images_container = document.getElementById('original_post_images');
    
    let original_images = [];
    if (original_images_container) {
        for (let i = 0; i < original_images_container.children.length; i++) {
            let imageNode = original_images_container.children[i];
            let tags = (imageNode.dataset.tags || '')
                .split(',')
                .map((tag) => tag.trim())
                .filter((tag) => tag.length > 0);
            original_images.push({
                id: imageNode.dataset.id || imageNode.textContent.trim(),
                category: imageNode.dataset.category || '',
                watermark: imageNode.dataset.watermark || '',
                tags: tags,
            });
        }
    }

    post_form = new PostEditForm(
        document.getElementById('post_edit_form'),
        original_title,
        original_content,
        original_images,
    );
</script>
{% endblock %}

app/posts/templates/posts/index.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<title>Posts</title>
{% endblock %}
{% block body %}
<div class="posts_index_container">
    <div class="posts_index_title_container">
        <h1 class="posts_index_title">Posts</h1>
    </div>
    {% for post in page.object_list %}
    <div class="posts_index_post_container">
        <a href="{% url 'posts:view' post.id %}">
            <div class="posts_index_post_title_container">
                <h2 class="posts_index_post_title">
                    {{ post.title }}
                </h2>
            </div>
            <div class="posts_index_post_date_container">
                <div class="posts_index_post_date">
                    {{ post.date_created }}
                </div>
            </div>
            <div class="posts_index_post_content_container">
                <div class="posts_index_post_content">
                    {{ post.preview }}
                </div>
            </div>
            {% if post.hasImages %}
                <div class="posts_index_post_images_container">
                    {% for image in post.album.preview %}
                        <div class="posts_index_post_image_container">
                            <img class="posts_index_post_image" src="{{ image.thumbnail.url }}" alt="{{ image.id }}">
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </a>
    </div>
    {% if not forloop.last %}
    <hr>
    {% endif %}
    {% endfor %}
    {% include "posts/paginator.html" %}
</div>

{% endblock %}

app/posts/templates/posts/paginator.html
<div class="pagination">
    {% if page.paginator.count > 0 %}
        <span class="step-links">
            {% if page.has_previous %}
                <a href="?page=1{{ pagination_query }}">&laquo; first</a>
                <a href="?page={{ page.previous_page_number }}{{ pagination_query }}">previous</a>
            {% endif %}

            {% if page.has_next %}
                <a href="?page={{ page.next_page_number }}{{ pagination_query }}">next</a>
                <a href="?page={{ page.paginator.num_pages }}{{ pagination_query }}">last &raquo;</a>
            {% endif %}
        </span>
        <div class="pagination_footer">
            <form class="posts_index_filters posts_index_filters_inline" method="get">
            <label>
                From
                <input type="date" name="start" value="{{ filters.start }}">
            </label>
            <label>
                To
                <input type="date" name="end" value="{{ filters.end }}">
            </label>
            <label>
                Sort
                <select name="sort">
                    <option value="newest"{% if filters.sort == "newest" %} selected{% endif %}>Newest</option>
                    <option value="oldest"{% if filters.sort == "oldest" %} selected{% endif %}>Oldest</option>
                </select>
            </label>
            <label>
                Per page
                <select name="max">
                    {% for option in per_page_options %}
                        <option value="{{ option }}"{% if filters.max == option %} selected{% endif %}>{{ option }}</option>
                    {% endfor %}
                </select>
            </label>
            <button type="submit">Apply</button>
            </form>
            <span class="current">
                Page {{ page.number }} of {{ page.paginator.num_pages }}
            </span>
        </div>
    {% endif %}
</div>

app/posts/templates/posts/view.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<script src="{% static 'posts/delete.js' %}"></script>
<script src="{% static 'lightbox.js' %}"></script>
<meta name="csrf-token" content="{{ csrf_token }}">
<title>{{ title }}</title>
<meta property="og:title" content="{{ title }}" />
<meta property="og:type" content="website" />
<meta property="og:url" content="{{ request.build_absolute_uri }}" />
{% if preview %}
<meta property="og:image" content="{{ preview }}" />
{% endif %}
<link rel="prefetch" href="{% static 'loading.svg' %}" />
{% endblock %}
{% block body %}
<div class="post_root">
    <div class="post_title">
        <h1>{{ title }}</h1>
    </div>
    <div class="post_date_container">
        <span class="post_date">{{ date }}</span>
    </div>
    {% if user.is_authenticated %}
    <div class="post_edit_container">
        <a class="post_edit_link" href="{% url 'posts:edit' id %}">Edit</a>
        <span class="post_edit_separator">|</span>
        <a class="post_delete_link" onclick="delete_post_clicked('{{ id }}')">Delete</a>
    </div>
    {% endif %}
    {% if content %}
    <div class="post_content_container">
        {% autoescape off %}
            {{ content }}
        {% endautoescape %}
    </div>
    {% endif %}
    {% if images %}
    <div class="album_images_container">
        {% for image in images %}
        <div class="album_image_container">
            <a class="album_image_link" href="{% url 'images:view' image.id %}">
                <img width="{{image.thumbnail.width}}px" height="{{image.thumbnail.height}}px" class="album_image" loading="lazy" alt="{{ image.id }}" src="{{ image.thumbnail.url }}">
            </a>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
<script>
    let lightbox = new LightBox();
</script>
{% endblock %}