app/maierbox/urls.py
from django.contrib import auth
from django.urls import include, path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.sitemaps.views import sitemap
from images.sitemap import WebImageSitemap
from posts.sitemap import PostSitemap
from albums.sitemap import WebImageAlbumSitemap
from categories.sitemap import ImageCategorySitemap
from .sitemap import StaticSitemap

sitemaps = {
    'sitemaps': {
        'static': StaticSitemap,
        'post': PostSitemap,
        'album': WebImageAlbumSitemap,
        'image': WebImageSitemap,
        'category': ImageCategorySitemap,
    }
}

urlpatterns = [
    path("", views.index, name="index"),
    path("peepers", views.eyes, name='peepers'),
    path("images/", include("images.urls")),
    path("tags/", include("tags.urls")),
    path("categories/", include("categories.urls")),
    path("watermarks/", include("watermarks.urls")),
    path("albums/", include("albums.urls")),
    path("posts/", include("posts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('sitemap.xml', sitemap, sitemaps, name='django.contrib.sitemaps.views.sitemap'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/tags/urls.py
from django.urls import path
from . import views

app_name = "tags"
urlpatterns = [
    path("list", views.list, name="list"),
    path("images/<str:tag>", views.view_images, name="view_images"),
]

app/watermarks/urls.py
from django.urls import path
from . import views

app_name = "watermarks"
urlpatterns = [
    path("add", views.add, name="add"),
    path("create", views.create, name="create"),
    path("list", views.list, name="list"),
]

app/watermarks/models.py
from django.db import models
from PIL import Image, ImageDraw, ImageFont
from django.contrib.auth.models import User
from .util import findFonts

WATERMARK_MARGIN=5
STROKE_PERCENT=5
WATERMARK_FIELDS=['text', 'size', 'font', 'transparency']

class Font(models.Model):
    name = models.CharField(
        null=False,
        blank=False,
        editable=False,
        max_length=64
    )
    family = models.CharField(
        null=False,
        blank=False,
        editable=False,
        max_length=64
    )
    style = models.CharField(
        null=False,
        blank=False,
        editable=False,
        max_length=64
    )
    path = models.CharField(
        null=False,
        blank=False,
        editable=False,
        max_length=256
    )

    @classmethod
    def populateFonts(cls):
        fonts = findFonts()
        fonts.sort(key=lambda x: f"{x['family']} {x['style']}")
        for font in fonts:
            if not cls.objects.filter(path=font['path']).exists():
                font_obj = cls(
                    name=font['name'],
                    family=font['family'],
                    style=font['style'],
                    path=font['path'],
                ).save()
                

class Watermark(models.Model):

    text = models.CharField(
        null=False,
        blank=False,
        editable=True,
        max_length=16
    )
    date_modified = models.DateTimeField(
        null=False,
        blank=False,
        auto_now=True,
        editable=False,
    )
    date_created = models.DateTimeField(
        null=False,
        blank=False,
        auto_now_add=True,
        editable=False,
    )
    size = models.SmallIntegerField(
        blank=False,
        null=False,
        editable=True
    )
    font = models.ForeignKey(
        to=Font,
        blank=False,
        null=False,
        on_delete=models.PROTECT,
        editable=False,
    )
    transparency = models.SmallIntegerField (
        null=False,
        blank=False,
        editable=True,
    )
    created_by = models.ForeignKey(
        to=User,
        blank=False,
        null=False,
        on_delete=models.PROTECT,
        editable=False,
    )

    def draw(self, image: Image):

        if image.mode != "RGBA":
            image = image.convert("RGBA")
        watermark = Image.new('RGBA', image.size, (255,255,255,0))
        draw = ImageDraw.Draw(watermark, 'RGBA')

        width, height = image.size
        if width > height:
            size = height
        else:
            size = width
        ratio = size / 200
        size = self.size * ratio
        
        font = ImageFont.truetype(self.font.path, int(size))
        text = self.text

        margin = WATERMARK_MARGIN * ratio
        x = width - margin
        y = height - margin

        alpha = int((100 - self.transparency) * 255 / 100)

        stroke_width = int(size * STROKE_PERCENT / 100)

        draw.text(
            (x, y), text,
            fill=(255, 255, 255, alpha),
            font=font,
            stroke_width=stroke_width,
            stroke_fill=(0, 0, 0, alpha),
            language='en',
            anchor='rs'
        )
        image = Image.alpha_composite(image, watermark)
        image = image.convert("RGB")
        return image

app/watermarks/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseNotAllowed, HttpRequest
from django.core.paginator import Paginator
from maierbox.util import JsonErrorResponse
from .models import Watermark, Font, WATERMARK_FIELDS
from django.contrib.auth.decorators import login_required

MAX_WATERMARKS=100

@login_required
def list(request: HttpRequest):

    if request.method != "GET":
        return HttpResponseNotAllowed(['GET'])
    
    if 'page' in request.GET:
        page = request.GET['page']
    else:
        page = 1
    
    paginator = Paginator(
        Watermark.objects.order_by("id"),
        per_page=MAX_WATERMARKS,
    )

    page = paginator.page(page)

    data = {
        'items': [
            {
                'id': watermark.id,
                'text': watermark.text,
            } for watermark in page.object_list.all()
        ]
    }

    if page.has_next():
        data['next'] = page.next_page_number()

    return JsonResponse(
        status=200,
        data=data
    )

@login_required
def add(request: HttpRequest):
    
    if request.method != "POST":
        return HttpResponseNotAllowed(['POST'])

    for field in WATERMARK_FIELDS:
        if not field in request.POST:
            return JsonErrorResponse(
                f'The "{field}" field is required'
            )
    
    data = {
        'created_by': request.user,
    }
    for field in WATERMARK_FIELDS:
        data[field] = request.POST[field]
    data['font'] = Font.objects.filter(id=request.POST['font']).first()
    watermark = Watermark(**data)
    watermark.save()

    return JsonResponse(
        status=200,
        data={
            'response': 'The watermark has been successfully added'
        }
    )

@login_required
def create(request: HttpRequest):
    if not Font.objects.first():
        Font.populateFonts()
    context = {
        'fonts': Font.objects.all()
    }
    return render(request, "watermarks/create.html", context)

app/watermarks/templates/watermarks/create.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<script src="{% static 'watermarks/watermark.js' %}"></script>
<title>Create Watermark</title>
{% endblock %}
{% block body %}
<div id="watermark_creation">
    <div>
        <form action="{% url 'watermarks:add' %}" method="post" id="watermark_form">
            {% csrf_token %}
            <fieldset>
                <legend><h1>Create a watermark</h1></legend>
                <table>
                    <tbody>
                        <tr>
                            <td>
                                <label for="watermark_text">Watermark Text</label>
                            </td>
                            <td>
                                <input type="text" id="watermark_text" name="text" onchange="update_watermark_preview();" value="Watermark">
                            </td>
                        </tr>
                        </tr>
                            <td>
                                <label for="watermark_font">Font</label>
                            </td>
                            <td>
                                <select id="watermark_font" name="font" onchange="update_watermark_preview();">
                                {% for font in fonts %}
                                    <option value="{{ font.id }}" data-style="{{ font.style }}" data-family="{{ font.family }}">{{ font.name }}</option>
                                {% endfor %}
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <label for="watermark_size">Font Size</label>
                            </td>
                            <td>
                                <input type="number" id="watermark_size" name="size" onchange="update_watermark_preview();" value="6">
                            </td>
                        <tr>
                        </tr>
                            <td>
                                <label for="watermark_transparency">Transparency</label>
                            </td>
                            <td>
                                <input type="range" id="watermark_transparency" name="transparency" min="0" max="100" value="80" onchange="update_watermark_preview();">
                            </td>
                        <tr>
                    </tbody>
                </table>
            </fieldset>
            <input type="submit" value="Submit">
        </form>
    </div>
    <div id="watermark_preview_container">
        <div id="watermark_preview">
            <div id="watermark_details_container">
                <div id="watermark_details">
                    <!-- <span id="watermark_preview_size"></span> -->
                    <span id="watermark_preview_ratio"></span>
                </div>
            </div>
            <div id="watermark_container">
                <span id="watermark"></span>
            </div>
        </div>
        <div id="watermark_preview_controls">
            <select id="watermark_control_ratio" onchange="on_ratio_changed(event);">
            </select>
            <select id="watermark_control_orientation" onchange="on_ratio_changed(event);">
                <option>Landscape</option>
                <option>Portrait</option>
            </select>
        </div>
    </div>
</div>
<script>
    const resizeObserver = new ResizeObserver(on_preview_resize);
    let preview = document.getElementById("watermark_preview");
    resizeObserver.observe(preview);
    let ratio = document.getElementById("watermark_ratio");
    populate_ratios(watermark_control_ratio);
</script>
{% endblock %}