app/categories/urls.py
from django.urls import path
from . import views

app_name = "categories"
urlpatterns = [
    path("list", views.list, name="list"),
    path("add", views.add_category, name="add_category"),
    path("images", views.image_index, name="image_index"),
    path("images/<str:category>", views.view_images, name="view_images"),
]

app/maierbox/urls.py
from django.contrib import auth
from django.urls import include, path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.sitemaps.views import sitemap
from images.sitemap import WebImageSitemap
from posts.sitemap import PostSitemap
from albums.sitemap import WebImageAlbumSitemap
from categories.sitemap import ImageCategorySitemap
from .sitemap import StaticSitemap

sitemaps = {
    'sitemaps': {
        'static': StaticSitemap,
        'post': PostSitemap,
        'album': WebImageAlbumSitemap,
        'image': WebImageSitemap,
        'category': ImageCategorySitemap,
    }
}

urlpatterns = [
    path("", views.index, name="index"),
    path("peepers", views.eyes, name='peepers'),
    path("images/", include("images.urls")),
    path("tags/", include("tags.urls")),
    path("categories/", include("categories.urls")),
    path("watermarks/", include("watermarks.urls")),
    path("albums/", include("albums.urls")),
    path("posts/", include("posts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('sitemap.xml', sitemap, sitemaps, name='django.contrib.sitemaps.views.sitemap'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/posts/urls.py
from django.urls import path, re_path
from . import views

app_name = "posts"
urlpatterns = [
    re_path(r"^view/(?P<id>[^/]+)/?$", views.view, name="view"),
    path("add", views.add, name="add"),
    path("create", views.create, name="create"),
    path("edit/<str:id>", views.edit, name="edit"),
    path("update/<str:id>", views.update, name="update"),
    path("delete/<str:id>", views.delete, name="delete"),
    path("", views.index, name="index"),
]

app/tags/urls.py
from django.urls import path
from . import views

app_name = "tags"
urlpatterns = [
    path("list", views.list, name="list"),
    path("images/<str:tag>", views.view_images, name="view_images"),
]

app/maierbox/views.py
from django.shortcuts import render, get_object_or_404

def index(request):
    return render(request, 'index.html')

def eyes(request):
    return render(request, 'eyes.html')

app/maierbox/templates/eyes.html
{% load static %}
<head>
    <script src="{% static 'eyes.js' %}"></script>
    <link rel="stylesheet" href="{% static 'eyes.css' %}">
    <title>0.0</title>
</head>
<body>
    <script>let eyes = new Eyes();</script>
</body>

app/maierbox/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<div class="homepage_container">
    <div class="homepage_title_container">
        <h1 class="homepage_title">Building Systems by Day,<br>Capturing Moments by Night</h1>
    </div>
    <div class="homepage_subtitle_container">
        <h3 class="homepage_subtitle">I’m Cullen Knight, a professional DevOps Engineer and amateur photographer in Austin, Texas, and this is my personal website. It's intended to serve as both an impetus for furthering my understanding of web development, as well as sharing my personal photography collection in a blog format for those who may be interested.</h3>
    </div>
    <div class="homepage_buttons_container">
        <div class="homepage_button_container">
            <a href="{% url 'posts:index' %}" class="homepage_button">Posts</a>
        </div>
        <div class="homepage_button_container">
            <a href="{% url 'categories:image_index' %}" class="homepage_button">Photography</a>
        </div>
        <div class="homepage_button_container">
            <a href="https://github.com/retrontology" class="homepage_button">Github</a>
        </div>
    </div>
</div>
{% endblock %}