app/categories/urls.py
from django.urls import path
from . import views

app_name = "categories"
urlpatterns = [
    path("list", views.list, name="list"),
    path("add", views.add_category, name="add_category"),
    path("images", views.image_index, name="image_index"),
    path("images/<str:category>", views.view_images, name="view_images"),
]

app/images/urls.py
from django.urls import path
from django.contrib.sitemaps.views import sitemap
from . import views
from .sitemap import WebImageSitemap 

app_name = "images"
urlpatterns = [
    path("upload", views.upload, name="upload"),
    path("add", views.add, name="add"),
    path("delete/<str:id>", views.delete, name="delete"),
    path("update-category/<str:id>", views.update_category, name="update_category"),
    path("update-tags/<str:id>", views.update_tags, name="update_tags"),
    path("view/<str:id>", views.view, name="view"),
]

app/maierbox/urls.py
from django.contrib import auth
from django.urls import include, path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.sitemaps.views import sitemap
from images.sitemap import WebImageSitemap
from posts.sitemap import PostSitemap
from albums.sitemap import WebImageAlbumSitemap
from categories.sitemap import ImageCategorySitemap
from .sitemap import StaticSitemap

sitemaps = {
    'sitemaps': {
        'static': StaticSitemap,
        'post': PostSitemap,
        'album': WebImageAlbumSitemap,
        'image': WebImageSitemap,
        'category': ImageCategorySitemap,
    }
}

urlpatterns = [
    path("", views.index, name="index"),
    path("peepers", views.eyes, name='peepers'),
    path("images/", include("images.urls")),
    path("tags/", include("tags.urls")),
    path("categories/", include("categories.urls")),
    path("watermarks/", include("watermarks.urls")),
    path("albums/", include("albums.urls")),
    path("posts/", include("posts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('sitemap.xml', sitemap, sitemaps, name='django.contrib.sitemaps.views.sitemap'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/tags/urls.py
from django.urls import path
from . import views

app_name = "tags"
urlpatterns = [
    path("list", views.list, name="list"),
    path("images/<str:tag>", views.view_images, name="view_images"),
]

app/images/models.py
from django.db import models
from django.core.files.uploadedfile import InMemoryUploadedFile
from categories.models import Category
from tags.models import Tag
from watermarks.models import Watermark
from io import BytesIO
from PIL import Image
from uuid import uuid4
from .util import gen_thumbnail, gen_scaled, SCALED_MAX
from os.path import splitext, basename
from django.urls import reverse


IMAGE_MAX_LENGTH = 64
ORIGINAL_IMAGE_DIR = "images/private"
BASE_IMAGE_DIR = "images/original"
SCALED_IMAGE_DIR = "images/scaled"
THUMBNAIL_IMAGE_DIR = "images/thumbnail"
ORIGINAL_SUBSAMPLING = 0
ORIGINAL_QUALITY = 95


class WebImage(models.Model):

    def _split_filename(self, filename):
        filename = basename(filename)
        return splitext(filename)
    
    
    def _upload_to_original(self, filename):
        ext = self._split_filename(filename)[1]
        return f'{ORIGINAL_IMAGE_DIR}/{self.id}{ext}'

    def _upload_to_base(self, filename):
        ext = self._split_filename(filename)[1]
        return f'{BASE_IMAGE_DIR}/{self.id}{ext}'
    
    def _upload_to_scaled(self, filename):
        ext = self._split_filename(filename)[1]
        return f'{SCALED_IMAGE_DIR}/{self.id}{ext}'
    
    def _upload_to_thumbnail(self, filename):
        ext = self._split_filename(filename)[1]
        return f'{THUMBNAIL_IMAGE_DIR}/{self.id}{ext}'

    id = models.UUIDField(
        primary_key=True,
        null=False,
        blank=False,
        default=uuid4,
        editable=False
    )
    name = models.CharField(
        null=False,
        blank=False,
        editable=False,
        max_length=IMAGE_MAX_LENGTH
    )
    tags = models.ManyToManyField(
        blank=True,
        to=Tag,
    )
    category = models.ForeignKey(
        to=Category,
        blank=False,
        null=True,
        on_delete=models.SET_NULL,
    )
    original = models.ImageField(
        null=True,
        blank=True,
        editable=False,
        upload_to=_upload_to_original,
    )
    full = models.ImageField(
        null=False,
        blank=False,
        editable=False,
        upload_to=_upload_to_base,
    )
    scaled = models.ImageField(
        null=True,
        blank=True,
        editable=False,
        upload_to=_upload_to_scaled,
    )
    thumbnail = models.ImageField(
        null=False,
        blank=False,
        editable=False,
        upload_to=_upload_to_thumbnail,
    )
    date_modified = models.DateTimeField(
        null=False,
        blank=False,
        auto_now=True,
        editable=False,
    )
    date_created = models.DateTimeField(
        null=False,
        blank=False,
        auto_now_add=True,
        editable=False,
    )
    watermark = models.ForeignKey(
        to=Watermark,
        blank=False,
        null=True,
        on_delete=models.PROTECT,
        editable=False,
    )
    unlisted = models.BooleanField(
        null=False,
        blank=False,
        default=False
    )
            

    @classmethod
    def from_image(cls, image, category=None, tags=None, watermark=None):
        id = uuid4()
        new_name = f'{id}.jpg'

        fields = {
            'name': image.name,
            'id': id,
            'category': category,
            'original': image,
        }

        image_bytes = BytesIO(image.read())
        image = Image.open(image_bytes)
        if image.mode != "RGB":
            image = image.convert("RGB")

        thumbnail = InMemoryUploadedFile(
            gen_thumbnail(image),
            'thumbnail',
            new_name,
            'JPEG',
            None,
            None
        )
        fields['thumbnail'] = thumbnail

        if watermark:
            image = watermark.draw(image)
        fields['watermark'] = watermark

        jpeg_data = BytesIO()
        image.save(
            jpeg_data,
            'jpeg',
            subsampling=ORIGINAL_SUBSAMPLING,
            quality=ORIGINAL_QUALITY
        )
        jpeg = InMemoryUploadedFile(
            jpeg_data,
            'resized',
            new_name,
            'JPEG',
            None,
            None
        )
        fields['full'] = jpeg

        if any(lambda x: x > SCALED_MAX for x in image.size):
            scaled = InMemoryUploadedFile(
                gen_scaled(image),
                'resized',
                new_name,
                'JPEG',
                None,
                None
            )
            fields['scaled'] = scaled
        else:
            fields['scaled'] = None

        image = WebImage(**fields)
        if tags:
            image.tags.set(tags)
        return image

    def get_scaled(self):
        return self.scaled.url if self.scaled else self.full.url

    def get_absolute_url(self):
        return reverse("images:view", args=[self.id])

    def __str__(self) -> str:
        return basename(self.full.path)

app/images/views.py
from django.shortcuts import render, get_object_or_404, redirect
from maierbox.util import JsonErrorResponse
from django.http import JsonResponse, HttpResponseNotAllowed, HttpRequest
from django.contrib.auth.decorators import login_required
from watermarks.models import Watermark
from .models import *
from categories.models import Category
from tags.models import Tag

def view(request: HttpRequest, id):
    if request.method != "GET":
        return HttpResponseNotAllowed(['GET'])
    
    referer = request.META.get('HTTP_REFERER')
    image = get_object_or_404(WebImage, id=id)
    context = {
        'image': image,
        'referer': referer,
        'preview': request.build_absolute_uri(image.thumbnail.url)
    }
    return render(request, 'images/view.html', context)

@login_required
def upload(request: HttpRequest):

    if request.method != "POST":
        return HttpResponseNotAllowed(['POST'])

    if not 'image' in request.FILES:
        JsonErrorResponse(
            data='The "image" field/file is required'
        )

    fields = {
        'image': request.FILES['image'],
    }

    if 'category' in request.POST:
        fields['category'] = Category.objects.get(category=request.POST['category'])
    else:
        fields['category'] = None
    
    if 'watermark' in request.POST:
        fields['watermark'] = Watermark.objects.get(id=request.POST['watermark'])
    else:
        fields['watermark'] = None

    image = WebImage.from_image(**fields)
    image.save()

    if 'tags' in request.POST:
        for tag in request.POST['tags'].split(','):
            tag, created = Tag.objects.get_or_create(tag=tag)
            if created:
                tag.save()
            image.tags.add(tag)

    image.save()
    
    return JsonResponse(
        status=200,
        data={
            'response': image.id
        }
    )

@login_required
def add(request: HttpRequest):
    if request.method != "GET":
        return HttpResponseNotAllowed(['GET'])
    
    return render(request, 'images/add.html')

@login_required
def delete(request: HttpRequest, id):
    if request.method != "DELETE":
        return HttpResponseNotAllowed(['DELETE'])
    
    image = get_object_or_404(WebImage, id=id)
    image.delete()
    return redirect('/')

@login_required
def update_category(request: HttpRequest, id):
    if request.method != "POST":
        return HttpResponseNotAllowed(['POST'])

    image = get_object_or_404(WebImage, id=id)
    category = request.POST.get('category', '').strip()
    if category == '':
        image.category = None
    else:
        try:
            image.category = Category.objects.get(category=category)
        except Category.DoesNotExist:
            return JsonErrorResponse(f'Category "{category}" does not exist')

    image.save()
    return JsonResponse(
        status=200,
        data={
            'category': category
        }
    )

@login_required
def update_tags(request: HttpRequest, id):
    if request.method != "POST":
        return HttpResponseNotAllowed(['POST'])

    image = get_object_or_404(WebImage, id=id)
    tags_str = request.POST.get('tags', '').strip()
    image.tags.clear()

    tags = []
    if tags_str != '':
        for tag in tags_str.split(','):
            cleaned_tag = tag.strip().lower()
            if cleaned_tag == '' or cleaned_tag in tags:
                continue
            tag_obj, created = Tag.objects.get_or_create(tag=cleaned_tag)
            if created:
                tag_obj.save()
            image.tags.add(tag_obj)
            tags.append(cleaned_tag)

    image.save()
    return JsonResponse(
        status=200,
        data={
            'tags': tags
        }
    )

app/images/templates/images/add.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<script src="{% static 'images/image_metadata_selects.js' %}"></script>
<script src="{% static 'images/upload.js' %}"></script>
<title>Upload Images</title>
{% endblock %}
{% block body %}
<div id="image_upload_form" class="image_upload_form"></div>
<script>
    image_upload_form = new ImageUploadForm(document.getElementById('image_upload_form'));
</script>
{% endblock %}

app/images/templates/images/view.html
{% extends "base.html" %}
{% load static %}
{% block head %}
<script src="{% static 'images/delete.js' %}"></script>
<script src="{% static 'images/image_metadata_selects.js' %}"></script>
<script src="{% static 'images/view.js' %}"></script>
<meta name="csrf-token" content="{{ csrf_token }}">
<title>View Image</title>
<meta property="og:title" content="View Image" />
<meta property="og:type" content="website" />
<meta property="og:url" content="{{ request.build_absolute_uri }}" />
<meta property="og:image" content="{{ preview }}" />
{% endblock %}
{% block return %}
    {% if referer != None %}
    <!-- <div class="header_return_container"> -->
        <!-- <a class="header_return" id="header_return" href="{{ referer }}">Return</a> -->
    <!-- </div> -->
    {% endif %}
{% endblock %}
{% block body %}
<div class="webimage_root">
    <div class="webimage_container">
        <a href="{{ image.full.url }}">
            <img class="webimage" alt="{{ image.id }}" src="{{ image.get_scaled }}">
        </a>
    </div>
    <div class="webimage_details">
        <div class="webimage_classifiers" id="webimage_classifiers">
            <div class="webimage_category" id="webimage_category_display">
                {% if image.category %}
                <span>Category:<a href="{% url 'categories:view_images' image.category %}">{{ image.category }}</a></span>
                {% endif %}
            </div>
            <div class="webimage_tags" id="webimage_tags_display">
                {% if image.tags.exists %}
                <span class="webimage_tags_label">Tags:</span>
                {% for tag in image.tags.all %}
                    <a class="webimage_tags_tag" href="{% url 'tags:view_images' tag.tag %}">{{ tag }}</a>
                {% endfor %}
                {% endif %}
            </div>
            {% if user.is_authenticated %}
            <div class="webimage_edit_panel" id="webimage_edit_panel">
                <div class="webimage_edit_sidebar" id="webimage_edit_sidebar"></div>
                <div class="webimage_edit_actions">
                    <button class="webimage_edit_save" type="button">Save</button>
                    <button class="webimage_edit_cancel" type="button">Cancel</button>
                </div>
            </div>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
        <div class="webimage_admin_container">
            <a class="webimage_edit_button">Edit</a>
            <span class="webimage_admin_separator">|</span>
            <a class="webimage_delete_button" onclick="delete_button_clicked('{{ image.id }}')">Delete</a>
        </div>
        <script>
            window.webimageEditContext = {
                id: "{{ image.id|escapejs }}",
                category: "{{ image.category|default_if_none:''|escapejs }}",
                tags: [{% for tag in image.tags.all %}"{{ tag.tag|escapejs }}"{% if not forloop.last %},{% endif %}{% endfor %}]
            };
        </script>
        {% endif %}
        <div class="webimage_uploaded">
            <span>Uploaded on {{ image.date_created.date }}</span>
        </div>
    </div>
</div>
{% endblock %}